#!/usr/bin/env python
"""
Usage:
    tabs-to-spaces <filepath>

"""
from difflib import unified_diff as differ
import sys
from xml.etree import cElementTree as ElementTree


def tabs_to_spaces(filepath):
    mode = "b" if sys.platform.startswith('win') else ""
    tabbed_string = ""
    with open(filepath, "rU" + mode) as fd:
        tabbed_string = fd.read()
    special = ('vcxproj', 'vcxproj.filters', 'xml')
    spacing = 4 if not filepath.endswith(special) else 2
    untabbed_string = tabbed_string.expandtabs(spacing)
    diff = list(differ(tabbed_string.splitlines(),
                       untabbed_string.splitlines(),
                       filepath, filepath))
    changed = '\n'.join(diff)
    if changed:
        with open(filepath, 'w' + mode) as fd:
            fd.write(untabbed_string)
        print "Tabs to Spaces:", filepath


if __name__ == "__main__":
    import sys

    argv = sys.argv[1:] if len(sys.argv) > 1 else []
    if not argv:
        print __doc__
    else:
        filepath = argv[0]
        extensions_to_convert = ('c', 'cpp', 'h', 'hpp', 'cs', 'py',
                                 'vcxproj', 'vcxproj.filters', 'xml')
        if filepath.endswith(extensions_to_convert):
            tabs_to_spaces(filepath)
