#!/usr/bin/env python

if __name__ == "__main__":
    import os
    from subprocess import call
    import sys

    argv = sys.argv[1:] if len(sys.argv) > 1 else []
    folder_path = os.path.dirname(__file__)
    if not folder_path:
        folder_path = os.getcwd()
    for root, folders, files in os.walk(folder_path):
        for filename in files:
            if filename.startswith('pre-commit') and filename != 'pre-commit':
                filepath = os.path.join(root, filename)
                cmd = [filepath] + argv
                call(cmd)
