#!/usr/bin/env python
"""
Usage:
    convert <filepath>

"""
from difflib import unified_diff as differ
import sys
from xml.etree import cElementTree as ElementTree


def strip_eol_spaces(filepath):
    mode = "b" if sys.platform.startswith('win') else ""
    extra_space_string = ""
    with open(filepath, "rU" + mode) as fd:
        extra_space_string = fd.read()
    compact_string = extra_space_string.rstrip()
    diff = list(differ(extra_space_string.splitlines(),
                       compact_string.splitlines(),
                       filepath, filepath))
    changed = '\n'.join(diff)
    if changed:
        with open(filepath, 'wU' + mode) as fd:
            fd.write(compact_string)
        print "Striped extra EOL Spaces:", filepath


if __name__ == "__main__":
    import sys

    argv = sys.argv[1:] if len(sys.argv) > 1 else []
    if not argv:
        print __doc__
    else:
        filepath = argv[0]
        extensions_to_convert = ('c', 'cpp', 'h', 'hpp', 'cs', 'py')
        if filepath.endswith(extensions_to_convert):
            strip_eol_spaces(filepath)
